### ISSUE TITLE
第4刷の誤植

### ISSUE THREAD

**Issue by takekapp1990** [drken1215/book_algorithm_solution#10]
楽しく読ませていただきました。errata.mdに載っていない軽微な誤植や改善点をいくつか見つけたので報告します。

* 319pの最後の行、「頂点番号がiであるような各頂点vに対して、」の後に続くa_iの式の右辺のΣの添え字がiであり、右辺と左辺でiの意味が異なるのがわかりづらい。
*  211pのcode12.4の34行目、「左詰め」→「右詰め」？
* 237pの本文の7行目から8行目にかけて、「どの頂点がどの頂点が子であるか」が誤植
* 296p 図16.12 の説明1行目、「フォート・ファルカーソン法」→「フォード・ファルカーソン法」

**Comment by drken1215** [comment]
大変ありがとうございます！

いずれも確認させていただきました。
ぜひとも、次回の版では対応したいと存じます。

**Comment by takekapp1990** [comment]
ご確認とerrataへの反映ありがとうございました。クローズします。
