### ISSUE TITLE
5章の章末問題7について

### ISSUE THREAD

**Issue by meshidenn** [drken1215/book_algorithm_solution#16]
例えば、S="pokemon", T="pachinko"とした時、回答のアルゴリズムを使うと最大共通文字列長が3と出てきますが、目視では1であるように見えます。下記回答で正しいのでしょうか。

https://github.com/drken1215/book_algorithm_solution/blob/master/solutions/chap05.md#57-%E6%9C%80%E9%95%B7%E5%85%B1%E9%80%9A%E9%83%A8%E5%88%86%E5%88%97%E5%95%8F%E9%A1%8C

**Comment by Kenkentake** [comment]
@meshidenn 
上記の場合では最大共通文字列＝"pko"となるため3で正しいと思います。

**Comment by meshidenn** [comment]
ご回答ありがとうございます。
連続している必要があると思いこんでいました。理解しました。ありがとうございます。
