### ISSUE TITLE
code_4_8.cpp と 章末問題4.2 のソースコードについて

### ISSUE THREAD

**Issue by zackey-heuristics** [drken1215/book_algorithm_solution#4]
### URL
- https://github.com/drken1215/book_algorithm_solution/blob/master/codes/chap04/code_4_8.cpp

- https://github.com/drken1215/book_algorithm_solution/blob/master/solutions/chap04.md

### 提案
code_4_8.cppについてですが，
ベースケースの2つについて，メモ化配列の値を更新しないままリターンを行っているため，  
memo[0] と memo[1] の中身は -1 のままで，フィボナッチ数列の解が入っていないままだと思います．  
従って，ベースケースでも，再帰呼び出しと同様に，メモ化しながら，リターンを行う方が良いのかなと思いました．

同様に，章末問題 4.2 のトリボナッチ数列でも，ベースケースの3つについて，  
メモ化配列の値を更新しないまま，リターンを行っていると思います．

### ソースコード
```cpp
long long fibo(int n) {
    // ベースケース
    if (n == 0) {
        return memo[n] = 0;
    } else if (n == 1) {
        return memo[n] = 1;
    }

    // メモをチェック (既に計算済みならば，答えをリターンする)
    if (memo[n] != -1) {
        return memo[n];
    }

    // 答えをメモ化しながら，再帰呼び出し
    return memo[n] = fibo(n - 1) + fibo(n - 2);
}
```

```cpp
long long tribonacci(int n) {
    using namespace std;

    // ベースケース
    if (n == 0) {
        return memo[n] = 0;
    } else if (n == 1) {
        return memo[n] = 0;
    } else if (n == 2) {
        return memo[n] = 1;
    }

    // メモをチェック (既に計算済みならば，答えをリターンする)
    if (memo[n] != -1) {
        return memo[n];
    }

    // 答えをメモしながら，再帰呼び出し
    return memo[n] = tribonacci(n - 1) + tribonacci(n - 2) + tribonacci(n - 3);
}
```

**Comment by zackey-heuristics** [comment]
よくよく考えたら，ベースケースで代入処理を行うと，度々代入が行われるので，よく無いですね．  
main関数で，メモ化配列のベースケース箇所の代入を行った方が良いと思いました．

**Comment by drken1215** [comment]
コメントありがとうございます！
確かに、ベースケースで代入するのを避ける気持ちがありました。
main 関数内でベースケース箇所の代入を行うのが確かに良さそうです。
